#!/usr/bin/env python3
import json
import sys
import argparse
import math
from time import sleep
import paho.mqtt.publish as mqtt_publish
from paho.mqtt.client import Client
from moontracker_common import *


class MoonTrackerCmd(object):

    def __init__(self):
        self.received_moontracker_state = None
        self.client = Client()
        self.client.enable_logger()
        self.client.on_connect = self.on_connect
        self.client.connect(MQTT_BROKER_HOST,
                            port=MQTT_BROKER_PORT,
                            keepalive=MQTT_BROKER_KEEP_ALIVE_SECS)
        self._wait_for_moontracker_state()
        self.client.loop_start()

    def build_argument_parser(self):
        azimuth_error_text = 'Azimuth angle must be between 0.0 and 360.0 degrees'
        elevation_error_text = 'Elevation angle must be between 0.0 and 180.0 degrees'

        def azimuth_range(value):
            value = float(value)
            if (0.0 > value or value > 360.0):
                raise argparse.ArgumentTypeError(azimuth_error_text)
            return value

        def elevation_range(value):
            value = float(value)
            if (0.0 > value or value > 180.0):
                raise argparse.ArgumentTypeError(elevation_error_text)
            return value

        parser = argparse.ArgumentParser()

        parser.add_argument('-a', '--azimuth', default=None,
                            type=azimuth_range, help='Azimuth angle between 0.0 and 360.0 degrees.')
        parser.add_argument('-e', '--elevation', default=None,
                            type=elevation_range, help='Elevation angle between 0.0 and 180.0 degrees.')

        on_off_group = parser.add_mutually_exclusive_group()
        on_off_group.add_argument('--on', action='store_true', default=None,
                                  help='Turns the moontracker device on.')
        on_off_group.add_argument('--off', action='store_true', default=None,
                                  help='Turns the moontracker device off.')

        parser.add_argument('-r', '--reset', action='store_true', default=None,
                            help="Resets the moon tracker's position.")

        return parser

    def _receive_moontracker_state(self, client, userdata, message):
        self.received_moontracker_state = json.loads(message.payload.decode('utf-8'))

    def _print_moontracker_state(self):
        print("Azimuth: {:.2f} Elevation: {:.2f} On: {}".format(
            self.received_moontracker_state['azimuth'],
            self.received_moontracker_state['elevation'],
            self.received_moontracker_state['on']))

    def on_connect(self, client, userdata, flags, rc):
        client.message_callback_add(TOPIC_TRACKER_CHANGE_NOTIFICATION,
                                    self._receive_moontracker_state)
        client.subscribe(TOPIC_TRACKER_CHANGE_NOTIFICATION)

    def update_moontracker_state(self):
        args = self.build_argument_parser().parse_args()

        if args.reset is not None:
            if not self.received_moontracker_state['on'] or (
                self.received_moontracker_state['azimuth'] == 0.0 and
                self.received_moontracker_state['elevation'] == 0.0):
                print('invalid')
                return
            else:
                self.received_moontracker_state['azimuth'] = 0.00
                self.received_moontracker_state['elevation'] = 0.00
                print('reset')

        else:
            if args.azimuth is not None:
                self.received_moontracker_state['azimuth'] = round(args.azimuth, FP_DIGITS)
            if args.elevation is not None:
                self.received_moontracker_state['elevation'] = round(args.elevation, FP_DIGITS)
            if args.on is not None:
                self.received_moontracker_state['on'] = True
            if args.off is not None:
                self.received_moontracker_state['on'] = False

        self.client.publish(TOPIC_SET_TRACKER_CONFIG,
                            json.dumps(self.received_moontracker_state
                                ).encode('utf-8'))

        sleep(0.1)
        self.client.loop_stop()

    def _wait_for_moontracker_state(self):
        for _ in range(10):
            if self.received_moontracker_state:
                return
            self.client.loop(timeout=0.05)
        raise Exception("Timeout waiting for moontracker state")


def main():
    moontracker_cmd = MoonTrackerCmd()

    if len(sys.argv) > 1:
        moontracker_cmd.update_moontracker_state()
    else:
        moontracker_cmd._print_moontracker_state()

if __name__ == '__main__':
    main()
